// <auto-generated />
namespace Genesis.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.0.1-alpha1-20811")]
    public sealed partial class Diff : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Diff));
        
        string IMigrationMetadata.Id
        {
            get { return "201308112151461_Diff"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
